services:
  - type: web
    name: urlshortener
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: MONGO_URI
        value: YOUR_MONGO_URI_HERE
      - key: DATABASE_NAME
        value: urlshortenerdb
      - key: PORT
        value: 8080
      - key: LANDING_PAGE
        value: ON
